### PR TITLE
Feature/ublas00004 simd gemm

### PR DESCRIPTION
**Pull request by imre-palik**
Pulling Michae Lehn's gemm implementation to ublas.

The patchset contains the generic implementation, and optimised kernels for gcc & clang.

Only testing was done on Linux, using these two compilers.

### CODE REVIEW

**Comment by nasosi** [comment]
Accepting and will run tests to see how it goes. Can you please change the BOOST_UBLAS_SMALL_MATRICES define to BOOST_UBLAS_LEGACY_PRODUCT?

**Comment by nasosi** [comment]
We also need to make the new implementation compile only for targeted architectures. Please check
https://sourceforge.net/p/predef/wiki/Architectures/
for relevant macro definitions. Something like:
#if defined(MSVC ) && !defined(BOOST_UBLAS_LEGACY_PRODUCT)
#ifndef _M_X64
#define BOOST_UBLAS_LEGACY_PRODUCT
#endif
#endif

#if defined(GCC)  && !defined(BOOST_UBLAS_LEGACY_PRODUCT)
#ifndef _x86_64
#define BOOST_UBLAS_LEGACY_PRODUCT
#endif
#endif

// I think the intel compiler defines more or less the gcc ones.
and so on.

**Comment by imre-palik** [comment]
As a new commit, or via rewriting history? 

    On Monday, 21 March 2016, 13:53, Nasos <notifications@github.com> wrote:
 

 Accepting and will run tests to see how it goes. Can you please change the BOOST_UBLAS_SMALL_MATRICES define to BOOST_UBLAS_LEGACY_PRODUCT?—

**Comment by imre-palik** [comment]
As far as I see, this is already done, using boost::predef.
I mean, the vectorised kernel only compiles for gcc or clang.  The baseline kernel should compile everywhere.
Or do you mean something different? 

    On Monday, 21 March 2016, 14:04, Nasos <notifications@github.com> wrote:
 

 We also need to make the new implementation compile only for targeted architectures. Please check
https://sourceforge.net/p/predef/wiki/Architectures/
for relevant macro definitions. Something like:
#if defined(MSVC ) && !defined(BOOST_UBLAS_LEGACY_PRODUCT)
#ifndef _M_X64
#define BOOST_UBLAS_LEGACY_PRODUCT
#endif
#endif#if defined(GCC) && !defined(BOOST_UBLAS_LEGACY_PRODUCT)
#ifndef _x86_64
#define BOOST_UBLAS_LEGACY_PRODUCT
#endif
#endif// I think the intel compiler defines more or less the gcc ones.
and so on.—

**Comment by nasosi** [comment]
I mean for different cpu architectures. The vectorization instructions 
won't be the same for example on ARM or PowerPC (or other) cpu 
architectures. We need to make sure we don't break the compilation on 
those. This is an important issue and we need to be very careful because 
ublas is used everywhere.

**Comment by imre-palik** [comment]
I am getting the vector size from boost::predef, so that shouldn't be an issue.Moreover if the underlying datatype is not vectorisable by the hardware (e.g., doubles on arm32) gcc will still compile valid code.  Though the performance might be bad.
But while doublechecking this, I found the following issues:- NR is not checked against the vector size, thus it can be set up to create bad results.- gescal() is buggy, and it can also corrupt the results.

I'll create a new pull request during the weekend.
 

    On Tuesday, 22 March 2016, 14:38, Nasos <notifications@github.com> wrote:
 

 I mean for different cpu architectures. The vectorization instructions 
won't be the same for example on ARM or PowerPC (or other) cpu 
architectures. We need to make sure we don't break the compilation on 
those. This is an important issue and we need to be very careful because 
ublas is used everywhere.

**Pull request merged**
