### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jdurancomas**

### CODE REVIEW

**Comment by nasosi** [comment]
Tested locally with gcc, clang and intel compilers and things look good. Will request a pull from boostorg::ublas.

**Comment by jdurancomas** [comment]
Feel free to pull the changes, but there are still warnings to fix.


2015-08-19 16:05 GMT+02:00 Nasos <notifications@github.com>:

**Comment by nasosi** [comment]
Yup! Also let's make a note to attempt to re-enable the SCL_WARNINGS by actually solving the issue. It is not very critical and it is actually tough (it has been in ublas for like since msvc started doing the relevant checks).

**Comment by jdurancomas** [comment]
In other boost libraries, this warning is already disabled:

[qduran@localhost libs]$ grep -rn "_SCL_SECURE_NO_WARNINGS" *
algorithm/example/Jamfile.v2:15:
<toolset>msvc:<define>_SCL_SECURE_NO_WARNINGS
array/test/array2.cpp:8:#ifndef _SCL_SECURE_NO_WARNINGS
array/test/array2.cpp:10:#  define _SCL_SECURE_NO_WARNINGS
circular_buffer/test/Jamfile.v2:18:
<toolset>msvc:<define>_SCL_SECURE_NO_WARNINGS
circular_buffer/example/jamfile.v2:26:
<toolset>msvc:<define>_SCL_SECURE_NO_WARNINGS
convert/test/jamfile.v2:26:
<toolset>msvc:<define>_SCL_SECURE_NO_WARNINGS
convert/example/jamfile.v2:19:
<toolset>msvc:<define>_SCL_SECURE_NO_WARNINGS
endian/test/benchmark.cpp:8:#ifndef _SCL_SECURE_NO_WARNINGS
endian/test/benchmark.cpp:9:# define _SCL_SECURE_NO_WARNINGS
endian/test/speed_test_functions.cpp:16:#ifndef _SCL_SECURE_NO_WARNINGS
endian/test/speed_test_functions.cpp:17:# define _SCL_SECURE_NO_WARNINGS
....



2015-08-19 19:52 GMT+02:00 Nasos <notifications@github.com>:

**Pull request merged**
