### PR TITLE
Add a simple convenience function to calculate the square norm (norm_2) of a vector

### PR DESCRIPTION
**Pull request by rdwampler**

### CODE REVIEW

**Comment by nasosi** [comment]
I think the loop in line 550 of functional.hpp will never finish for an unsigned type. Can you please amend?

i.e. try to run this:
#include <iostream>
int main()
{
std::size_t i = 1000000;
while (--i >= 0 )
{
std::cout << i << std::endl;
}
return 0;
}

**Comment by rdwampler** [comment]
> I think the loop in line 550 of functional.hpp will never finish for an unsigned type.

This loop seems to be a common idiom in this file. [Digging into it further] (https://github.com/uBLAS/ublas/blob/master/include/boost/numeric/ublas/vector_expression.hpp#L1544-L1545), it looks like the expectation for `size` is to be of `difference_type` (i.e., signed) and not `size_type`. Perhaps we can constraint these functions to guard against the infinite loop like so?
```
typedef typename V::difference_type difference_type
template<class I>
result_type apply (difference_type size, I it) 
```

**Comment by nasosi** [comment]
I think you are right. I will merge the pull request. I don't think we need to worry right now because it is only in a couple of places that the specific overload is called and would immediately show on the regression tests if something goes wrong.

**Comment by nasosi** [comment]
Ok it seems intel, gcc and clang are ok. Will be in the next merge to boostorg.

**Comment by rdwampler** [comment]
Thanks!

**Pull request merged**
